<?php

declare(strict_types=1);

namespace App\Domain\Sales\Models;

use App\Domain\Crm\Models\Customer;
use App\Domain\Identity\Models\User;
use App\Domain\Inventory\Models\StockLocation;
use App\Support\Money\MoneyCast;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * The in-progress basket, persisted.
 *
 * OSPOS kept this in `$_SESSION`, so a browser crash, a session timeout or a
 * shift handover destroyed the basket, and "suspending" meant writing a
 * half-real row into `sales` with `sale_status = SUSPENDED` that every sales
 * query then had to filter back out.
 *
 * `client_uuid` is generated by the register before the first request, which is
 * what lets the offline PWA queue a cart locally and replay it safely.
 */
class Cart extends Model
{
    public const STATUS_ACTIVE = 'active';

    public const STATUS_SUSPENDED = 'suspended';

    public const STATUS_COMPLETED = 'completed';

    public const STATUS_ABANDONED = 'abandoned';

    protected $guarded = ['id'];

    protected function casts(): array
    {
        return [
            'suspended_at' => 'datetime',
            'abandoned_at' => 'datetime',
            'tip_amount' => MoneyCast::class,
        ];
    }

    public function lines(): HasMany
    {
        return $this->hasMany(CartLine::class)->orderBy('line_number');
    }

    public function payments(): HasMany
    {
        return $this->hasMany(CartPayment::class);
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /** Whoever took the order -- set once at creation and never reattributed, unlike user(). */
    public function waiter(): BelongsTo
    {
        return $this->belongsTo(User::class, 'waiter_id');
    }

    public function terminal(): BelongsTo
    {
        return $this->belongsTo(Terminal::class);
    }

    public function shift(): BelongsTo
    {
        return $this->belongsTo(Shift::class);
    }

    public function dinnerTable(): BelongsTo
    {
        return $this->belongsTo(DinnerTable::class);
    }

    public function stockLocation(): BelongsTo
    {
        return $this->belongsTo(StockLocation::class);
    }

    public function nextLineNumber(): int
    {
        return (int) $this->lines()->max('line_number') + 1;
    }

    public function scopeSuspended(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_SUSPENDED);
    }
}
