<div>
    @section('title', $expenseCategory ? 'Edit expense category' : 'New expense category')

    @php $fieldClass = 'h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-950 shadow-sm outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20 dark:border-slate-700 dark:bg-slate-950 dark:text-white'; @endphp

    <div class="mx-auto max-w-5xl space-y-6">
        <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-sm font-medium text-emerald-700 dark:text-emerald-400">Finance</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 dark:text-white">{{ $expenseCategory ? 'Edit expense category' : 'New expense category' }}</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-400">Create a clear reporting label for expenses.</p></div>
            <a href="{{ route('expense-categories.index') }}" class="inline-flex h-9 items-center gap-1.5 self-start text-sm font-semibold text-slate-600 hover:text-emerald-700 dark:text-slate-300 dark:hover:text-emerald-300 sm:self-auto"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="m15 18-6-6 6-6M9 12h12"/></svg>Back to categories</a>
        </header>

        @if (session('status'))<div role="status" class="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{{ session('status') }}</div>@endif

        <form wire:submit="save" class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.7fr)] lg:items-start">
            <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
                <header class="border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><h3 class="text-base font-semibold text-slate-950 dark:text-white">Category details</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Name and code appear in expense entry and reporting.</p></header>
                <div class="space-y-5 p-5 sm:p-6">
                    <div><label for="name" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Category name <span class="text-rose-600">*</span></label><input wire:model.live="name" id="name" type="text" maxlength="255" autocomplete="off" placeholder="e.g. Utilities" required class="{{ $fieldClass }}">@error('name')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="code" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Category code <span class="text-rose-600">*</span></label><input wire:model.live="code" id="code" type="text" maxlength="32" autocomplete="off" placeholder="e.g. UTILITIES" required class="{{ $fieldClass }} font-mono">@error('code')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror<p class="mt-1.5 text-xs text-slate-500 dark:text-slate-400">A unique short identifier for exports and internal references.</p></div>
                    <div><label for="description" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Description <span class="font-normal text-slate-500">(optional)</span></label><textarea wire:model.live.debounce.300ms="description" id="description" rows="4" placeholder="Describe which expenses belong in this category" class="w-full rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20 dark:border-slate-700 dark:bg-slate-950 dark:text-white"></textarea>@error('description')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                </div>
                <footer class="flex flex-col-reverse gap-3 border-t border-slate-200 bg-slate-50/70 px-5 py-4 sm:flex-row sm:justify-end dark:border-slate-800 dark:bg-slate-950/40 sm:px-6"><a href="{{ route('expense-categories.index') }}" class="inline-flex h-10 items-center justify-center rounded-md px-4 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button type="submit" wire:loading.attr="disabled" wire:target="save" class="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-emerald-700 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-60 dark:bg-emerald-600 dark:hover:bg-emerald-500"><svg wire:loading.remove wire:target="save" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 6M4 5h12l4 4v10H4z"/></svg><svg wire:loading wire:target="save" class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.4 0 0 5.4 0 12h4z"/></svg><span wire:loading.remove wire:target="save">{{ $expenseCategory ? 'Save category' : 'Create category' }}</span><span wire:loading wire:target="save">Saving…</span></button></footer>
            </section>

            <aside class="space-y-4 lg:sticky lg:top-20">
                <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><header class="border-b border-slate-200 px-4 py-3.5 dark:border-slate-800"><h3 class="text-sm font-semibold text-slate-900 dark:text-white">Preview</h3><p class="mt-0.5 text-xs text-slate-500 dark:text-slate-400">How this label appears in expense records.</p></header><div class="space-y-3 p-4"><div><p class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Category</p><p class="mt-1 text-base font-semibold text-slate-900 dark:text-white">{{ $name ?: 'Category name' }}</p></div><div class="border-t border-slate-100 pt-3 dark:border-slate-800"><p class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Code</p><p class="mt-1 font-mono text-sm font-medium text-slate-800 dark:text-slate-200">{{ $code ?: 'CODE' }}</p></div><div class="border-t border-slate-100 pt-3 dark:border-slate-800"><p class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Description</p><p class="mt-1 break-words text-sm text-slate-600 dark:text-slate-400">{{ $description ?: 'No description' }}</p></div></div></section>
                @if ($expenseCategory)<div class="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p class="text-sm font-semibold text-slate-900 dark:text-white">Existing category</p><p class="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Changing the name or code updates the label for expenses already assigned to this category.</p></div>@endif
            </aside>
        </form>
    </div>
</div>
