<div>
    @section('title', $expense ? 'Edit expense' : 'New expense')

    @php
        $fieldClass = 'h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-950 shadow-sm outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20 dark:border-slate-700 dark:bg-slate-950 dark:text-white';
        $moneyPattern = '/^\d{1,15}(\.\d{1,2})?$/';
        $amountIsValid = preg_match($moneyPattern, trim($amount)) === 1;
        $taxIsValid = preg_match($moneyPattern, trim($tax_amount)) === 1;
        $previewTotal = $amountIsValid && $taxIsValid
            ? \App\Support\Money\Money::of($amount)->plus(\App\Support\Money\Money::of($tax_amount))
            : null;
    @endphp

    <div class="mx-auto max-w-6xl space-y-6">
        <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-sm font-medium text-emerald-700 dark:text-emerald-400">Finance</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 dark:text-white">{{ $expense ? 'Edit expense' : 'Record expense' }}</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-400">Capture the amount, tax, category, and payment context.</p></div>
            <a href="{{ route('expenses.index') }}" class="inline-flex h-9 items-center gap-1.5 self-start text-sm font-semibold text-slate-600 hover:text-emerald-700 dark:text-slate-300 dark:hover:text-emerald-300 sm:self-auto"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="m15 18-6-6 6-6M9 12h12"/></svg>Back to expenses</a>
        </header>

        @if (session('status'))<div role="status" class="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{{ session('status') }}</div>@endif

        @if ($expenseCategories->isEmpty())
            <div role="alert" class="flex flex-col gap-3 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 sm:flex-row sm:items-center sm:justify-between dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><p>Create an expense category before recording an expense.</p><a href="{{ route('expense-categories.create') }}" class="inline-flex h-9 items-center justify-center rounded-md border border-amber-300 px-3 font-semibold hover:bg-amber-100 dark:border-amber-800 dark:hover:bg-amber-900/40">Create category</a></div>
        @endif

        <form wire:submit="save" class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.68fr)] lg:items-start">
            <div class="space-y-5">
                <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
                    <header class="border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><h3 class="text-base font-semibold text-slate-950 dark:text-white">Expense details</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Describe and classify this cost.</p></header>
                    <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                        <div><label for="description" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Description <span class="font-normal text-slate-500">(optional)</span></label><input wire:model.live="description" id="description" type="text" autocomplete="off" placeholder="e.g. Monthly electricity bill" class="{{ $fieldClass }}">@error('description')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="expense_category_id" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Category <span class="text-rose-600">*</span></label><select wire:model.live="expense_category_id" id="expense_category_id" required class="{{ $fieldClass }}"><option value="">Select a category</option>@foreach ($expenseCategories as $category)<option value="{{ $category->id }}">{{ $category->name }} · {{ $category->code }}</option>@endforeach</select>@error('expense_category_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="spent_on" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Expense date <span class="text-rose-600">*</span></label><input wire:model.live="spent_on" id="spent_on" type="date" required class="{{ $fieldClass }}">@error('spent_on')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="reference" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Reference <span class="font-normal text-slate-500">(optional)</span></label><input wire:model.live="reference" id="reference" type="text" autocomplete="off" placeholder="Invoice or receipt number" class="{{ $fieldClass }}">@error('reference')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    </div>
                </section>

                <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
                    <header class="border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><h3 class="text-base font-semibold text-slate-950 dark:text-white">Amount and tax</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Amounts are recorded in {{ $expense?->currency ?? \App\Support\Money\Money::currency() }}.</p></header>
                    <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                        <div><label for="amount" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Amount before tax <span class="text-rose-600">*</span></label><div class="relative"><input wire:model.live.debounce.300ms="amount" id="amount" type="text" inputmode="decimal" autocomplete="off" placeholder="0.00" required class="{{ $fieldClass }} pr-16 text-right tabular-nums"><span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs font-semibold text-slate-400">{{ $expense?->currency ?? \App\Support\Money\Money::currency() }}</span></div><p class="mt-1.5 text-xs text-slate-500 dark:text-slate-400">Up to two decimal places.</p>@error('amount')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="tax_amount" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Tax amount <span class="text-rose-600">*</span></label><div class="relative"><input wire:model.live.debounce.300ms="tax_amount" id="tax_amount" type="text" inputmode="decimal" autocomplete="off" placeholder="0.00" required class="{{ $fieldClass }} pr-16 text-right tabular-nums"><span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs font-semibold text-slate-400">{{ $expense?->currency ?? \App\Support\Money\Money::currency() }}</span></div><p class="mt-1.5 text-xs text-slate-500 dark:text-slate-400">Enter zero when no tax applies.</p>@error('tax_amount')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    </div>
                </section>

                <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
                    <header class="border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><h3 class="text-base font-semibold text-slate-950 dark:text-white">Related records</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Link optional supplier, location, and payment information.</p></header>
                    <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                        <div><label for="supplier_id" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Supplier <span class="font-normal text-slate-500">(optional)</span></label><select wire:model.live="supplier_id" id="supplier_id" class="{{ $fieldClass }}"><option value="">No supplier</option>@foreach ($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->company_name }}</option>@endforeach</select>@error('supplier_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="stock_location_id" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Location <span class="font-normal text-slate-500">(optional)</span></label><select wire:model.live="stock_location_id" id="stock_location_id" class="{{ $fieldClass }}"><option value="">No location</option>@foreach ($stockLocations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select>@error('stock_location_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                        <div class="sm:col-span-2"><label for="payment_method_id" class="mb-1.5 block text-sm font-semibold text-slate-700 dark:text-slate-300">Payment method <span class="font-normal text-slate-500">(optional)</span></label><select wire:model.live="payment_method_id" id="payment_method_id" class="{{ $fieldClass }}"><option value="">Not specified</option>@foreach ($paymentMethods as $method)<option value="{{ $method->id }}">{{ $method->name }}</option>@endforeach</select>@error('payment_method_id')<p class="mt-1.5 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
                    </div>
                </section>
            </div>

            <aside class="space-y-5 lg:sticky lg:top-20">
                <section class="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><header class="border-b border-slate-200 px-4 py-3.5 dark:border-slate-800"><h3 class="text-sm font-semibold text-slate-900 dark:text-white">Expense total</h3><p class="mt-0.5 text-xs text-slate-500 dark:text-slate-400">Amount plus tax</p></header><div class="space-y-3 p-4"><div class="flex justify-between gap-3 text-sm"><span class="text-slate-500 dark:text-slate-400">Amount</span><span class="font-medium tabular-nums text-slate-800 dark:text-slate-200">{{ $amountIsValid ? \App\Support\Money\Money::of($amount) : '—' }}</span></div><div class="flex justify-between gap-3 text-sm"><span class="text-slate-500 dark:text-slate-400">Tax</span><span class="font-medium tabular-nums text-slate-800 dark:text-slate-200">{{ $taxIsValid ? \App\Support\Money\Money::of($tax_amount) : '—' }}</span></div><div class="flex justify-between gap-3 border-t border-slate-100 pt-3 dark:border-slate-800"><span class="text-sm font-semibold text-slate-700 dark:text-slate-300">Total</span><span class="text-lg font-bold tabular-nums text-slate-950 dark:text-white">{{ $previewTotal ?? 'Enter valid amounts' }}</span></div></div></section>
                <section class="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h3 class="text-sm font-semibold text-slate-900 dark:text-white">Entry summary</h3><dl class="mt-3 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500 dark:text-slate-400">Category</dt><dd class="truncate text-right font-medium text-slate-800 dark:text-slate-200">{{ $expenseCategories->firstWhere('id', $expense_category_id)?->name ?? 'Not selected' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500 dark:text-slate-400">Date</dt><dd class="text-right font-medium text-slate-800 dark:text-slate-200">{{ $spent_on ? \Illuminate\Support\Carbon::parse($spent_on)->format('M j, Y') : 'Not set' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500 dark:text-slate-400">Supplier</dt><dd class="truncate text-right font-medium text-slate-800 dark:text-slate-200">{{ $suppliers->firstWhere('id', $supplier_id)?->company_name ?? '—' }}</dd></div></dl></section>
            </aside>

            <footer class="sticky bottom-0 z-10 -mx-1 flex flex-col-reverse gap-3 border-t border-slate-200 bg-white/95 px-1 py-3 backdrop-blur sm:flex-row sm:items-center sm:justify-end lg:col-span-2 dark:border-slate-800 dark:bg-slate-950/95"><a href="{{ route('expenses.index') }}" class="inline-flex h-10 items-center justify-center rounded-md px-4 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button type="submit" wire:loading.attr="disabled" wire:target="save" class="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-emerald-700 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-60 dark:bg-emerald-600 dark:hover:bg-emerald-500"><svg wire:loading.remove wire:target="save" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 6M4 5h12l4 4v10H4z"/></svg><svg wire:loading wire:target="save" class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.4 0 0 5.4 0 12h4z"/></svg><span wire:loading.remove wire:target="save">{{ $expense ? 'Save expense' : 'Record expense' }}</span><span wire:loading wire:target="save">Saving…</span></button></footer>
        </form>
    </div>
</div>
